from enum import Enum

class MyLandmark(Enum):
    HEAD = 0
    RIGHT_SHOULDER = 1
    LEFT_SHOULDER = 2
    NECK = 3
    LEFT_ELBOW = 4
    LEFT_WRIST = 5
    LEFT_INDEX = 6
    LEFT_THUMB_MCP = 7
    LEFT_PINKY = 8
    LEFT_THUMB_IP = 9
    LEFT_THUMB_TIP = 10
    LEFT_HIP = 11
    RIGHT_HIP = 12
    LEFT_KNEE = 13
    RIGHT_KNEE = 14
    LEFT_HEEL = 15
    LEFT_FOOT_TIP = 16
    RIGHT_HEEL = 17
    RIGHT_FOOT_TIP = 18
    RIGHT_ELBOW = 19
    RIGHT_WRIST = 20
    RIGHT_PINKY = 21
    RIGHT_INDEX = 22
    RIGHT_THUMB_TIP = 23
    RIGHT_THUMB_MCP = 24
    RIGHT_THUMB_IP = 25
    LEFT_ANKLE = 26
    RIGHT_ANKLE = 27
    LEFT_EYE = 28
    RIGHT_EYE = 29
    LEFT_EAR = 30
    RIGHT_EAR = 31